#!/usr/bin/env ruby
#
# Copyright (c) 2008 The Kaphan Foundation
#
# Possession of a copy of this file grants no permission or license
# to use, modify, or create derivate works.
# Please contact info@peerworks.org for further information.
#
dir = File.dirname(__FILE__)
exit(system("spec -o #{File.join(dir, 'spec.opts')} #{Dir.glob(File.join(dir, '*_spec.rb')).join(' ')}"))
