#!/usr/bin/env ruby
#
# Copyright (c) 2008 The Kaphan Foundation
#
# Possession of a copy of this file grants no permission or license
# to use, modify, or create derivate works.
# Please contact info@peerworks.org for further information.
#

exit(system("spec #{Dir.glob(File.join(File.dirname(__FILE__), '*_spec.rb')).join(' ')}"))
